export const LOAD_RELEASES_SUCCESS = 'LOAD_RELEASES_SUCCESS';
export const LOAD_ALL_MODULES_SUCCESS = 'LOAD_ALL_MODULES_SUCCESS';
export const LOAD_MODULES_FOR_RELEASE_SUCCESS = 'LOAD_MODULES_FOR_RELEASE_SUCCESS';
export const BUILD_FORM_STATE = 'BUILD_FORM_STATE';
export const LOAD_ALL_BUILD_REFERENCES_SUCCESS = 'LOAD_ALL_BUILD_REFERENCES_SUCCESS';
export const VIEW_SELECTED = 'VIEW_SELECTED';
export const CREATE_BUILD_INIT_SUCCESS = 'CREATE_BUILD_INIT_SUCCESS';